### ISSUE TITLE
Database structure

### ISSUE THREAD

**Issue by Adam-Henrie** [Adam-Henrie/LiveCourier-UT3#10]
I am curious how we should be setting up the database structure based on how Firebase stores its info in Collections and Documents.  I will have some info on roughly how it should work in the UML (issue) but I need specifics on fields that need to be added to collections of data such as the stores that we will be selling stuff as well as how those stores categorize their items. We need User fields such as name, address, order history? Maybe order history needs to be a separate collection of data? Etc.

**Comment by mattmaloof** [comment]
Great video explaining how to create a password reset option for email users of the app in Android Firebase.

https://www.youtube.com/watch?v=t8vUdt1eEzE&ab_channel=CodingDemos

**Comment by Adam-Henrie** [comment]
I believe I have figured out about 90% of the database structure. The current version of that structure is modeled in the OneNote document that houses the project UML.
