### ISSUE TITLE
Suggested Android APP IDE

### ISSUE THREAD

**Issue by Adam-Henrie** [Adam-Henrie/LiveCourier-UT3#2]
Current suggestion is Android Studio. Any other suggestions can be added via a comment on the (issue). We can close this issue once we pick one. 
https://developer.android.com/studio/?authuser=1

**Comment by Adam-Henrie** [comment]
So far I have found out that there are a variety of other IDEs that have plugins for Android app development that include: Eclipse, Netbeans, Visual Studio, and Intellij Idea. There are also to game engine dev apps. Unreal Engine, and Unity. 

I would like to go with Android Studio for a couple of reasons. I believe that it has the most built in features and it also has a built in Android app emulator for debugging that we could use alongside another standalone emulator such as Bluestacks.
However, Visual studio should have support for Java coding as well as plugins. I know a lot of people like to use Visual Studio. It just may take so finagling to work. 

Let me know if you guys have any other thoughts or suggestions.

**Comment by Amrasoronr** [comment]
I believe as long as everyone has an android phone and can test it out, using android studio is a great idea!

**Comment by milanp1130** [comment]
I am familiar with both android studio and visual studios, either or would be great to use.

**Comment by Adam-Henrie** [comment]
No other suggestions added. Android Studio seems to be the best bet. Moving forward with research on how to use it as well as how to use Google Firestore/Firebase to do database storage.
