### ISSUE TITLE
Create Speeches

### ISSUE THREAD

**Issue by mattmaloof** [Adam-Henrie/LiveCourier-UT3#23]
Both PM and SM work together to make sure to stay in the 19 > x <= 24 time range with their speeches written down and practiced.  Do not read off slides.

**Comment by Adam-Henrie** [comment]
Changes to this include:
* Total time 30-35 min
* Description of the libraries, tech platforms, and emulators used to run the app
* Explain our system as a design pattern as outlined in ch.7 sec. 7.2 of book
* Live demonstration of the completed system.
*

**Comment by Adam-Henrie** [comment]
About half done with presentation so far.
