### ISSUE TITLE
Research dump GPS tutorials.

### ISSUE THREAD

**Issue by Adam-Henrie** [Adam-Henrie/LiveCourier-UT3#3]
Here we can post all of our research regarding tutorials on how to implement GPS into our courier app. Any addition changes to the issue can be timestamped. (never mind on this) I found out that people can comment on the issue below when the click on it or they can say that it is complete and mark it complete. 
https://www.youtube.com/watch?v=V62sxpyxapU&ab_channel=shadsluiter
Added 3:12pm 2/1/21

**Comment by milanp1130** [comment]
Watched the video, was a great explanation would help a lot. Everyone should watch that video for a better understanding.

**Comment by Adam-Henrie** [comment]
Here is some extra research information for using Firebase Storage for images. https://firebase.google.com/docs/storage/android/start

**Comment by mattmaloof** [comment]
This link explains how we can draw a line between two points (client location, service location) on a map that follows roads using android studio (gif of explanation below link).

[https://www.journaldev.com/13373/android-google-map-drawing-route-two-points](url)

![Alt Text](https://cdn.journaldev.com/wp-content/uploads/2016/12/android-map-routing-output-2.gif)

**Comment by mattmaloof** [comment]
Another option for routing -- https://docs.mapbox.com/android/navigation/guides/route-progress/

Includes RouteProgress class which may be useful to include distance measurements and the percentage of the route that's been completed.

**Comment by Adam-Henrie** [comment]
I just found this today which I should be able to implement on top of the Maps API to do a quick distance and time calculation. 
https://developers.google.com/maps/documentation/distance-matrix/overview?authuser=1

**Comment by Adam-Henrie** [comment]
Most of the research is done. The only current issue is dealing with how to implement the given Google APIs to help us with development of distance from customer and time till arrival. The programmers in the next sprint should be able to deal with that.
