### ISSUE TITLE
UML rough model of app.

### ISSUE THREAD

**Issue by Adam-Henrie** [Adam-Henrie/LiveCourier-UT3#6]
We need a UML model outlining roughly what we expect to need to develop for the app. Which systems will communicate with which. What the GUI will look like etc.

**Comment by Adam-Henrie** [comment]
Here is a rough UML model of the app as well as APP screens. Changes of intent and transitions to new screens. I am still fuzzy on how we should implement the database. I will have to continue to tweak it. I am posting a PDF of what I have drawn so far. I will also be posting a sharable link to the open and editable OneNote Document of which you all can edit and add to!

The vector graphics for natural writing do not translate to full writing detail for the smaller letters in the PDF so to see it in the pure writing form that it was captured in, I would suggest just going straight to the OneNote doc to review it. 

[https://app.zenhub.com/files/334029424/c6e7b026-4112-42b8-a728-03d18306aaff/download](https://app.zenhub.com/files/334029424/c6e7b026-4112-42b8-a728-03d18306aaff/download)

https://1drv.ms/u/s!AjldN1v-D__tnZodocBtWzCCcWlEjQ

You may need to make sure that you have a Microsoft Account to use the full functionality of One Note online but I think it allows people with the edit link to edit it as a guest too. 

You can zoom in on the document by using ctrl + scroll-wheel if I am not mistaken. 

Let me know what you guys think!

**Comment by mattmaloof** [comment]
Just reviewed it more thoroughly, I believe this is a great general guideline/model for us to work towards to have a foundation for adding more features to the app.

Some recommendations/thoughts to consider that we might not have time for but that I didn't see on the UML diagram:

Rate delivery out of 5 stars after it's dropped off at your house
Tip (before or after delivery?)
Some way to get % money back or credit for future orders if an order was missing an item or something (far far reach)

Possibly menu dots pages:

Profile page (can change first / last name, maybe password, maybe saved addresses to deliver to)
Saved payment method page (for easier drop-down selection for future orders)
Feedback page? (can send email to support for any concerns etc.)

**Comment by milanp1130** [comment]
Liked the feature about having a page to leave feedback and also we must have a page for when someone doesn’t even a delivery that’s a must, I’m not really sure how but i will try my best to look more into that. Firestone folders with different names of car company’s, what to buy from the food spots or even like Walmart or something so the person that orders would know who the driver is. Should have a feature where it tells what the delivery is driving.
